version: '3.9'
services:
  app:
    build: .
    environment:
      BOT_TOKEN: ""
      DB_DSN: "root:root@tcp(db:3306)/app?charset=utf8mb4&parseTime=True&loc=Local"
    depends_on: [db]
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app